export default data = [
	{
		id: 1,
		tenantName: "Michael Nandi",
		read: true,
		msg: "your offer have been accepted having an amount or number that is not known or not stated, or being a part of something: Let's get some work done. Some stories he wrote were made into movies.",
	},
	{
		id: 2,
		tenantName: "juma nao",
		read: false,
		msg: "your offer has been accepted having an amount or number that is not known or not stated, or being a part of something: Let's get some work done. Some stories he wrote were made into movies.",
	},
	{
		id: 3,
		tenantName: "shadrack Mwakipembe",
		read: true,
		msg: "message text here",
	},
	{
		id: 4,
		tenantName: "Larry Gods",
		price: 80000,
		read: true,
		msg: "message text here",
	},
	{
		id: 5,
		tenantName: "Ally Jr",

		read: false,
		msg: "message text here",
	},
	{
		id: 6,
		tenantName: "Sam Jones",
		read: false,
		msg: "message text here",
	},
	{
		id: 7,
		tenantName: "Harmes",
		read: false,
		msg: "message text here",
	},
	{
		id: 8,
		tenantName: "Sam Smith",
		price: 16000,
		read: false,
		msg: "message text here",
	},
	{
		id: 9,
		tenantName: "Sam Smith",
		price: 16000,
		read: true,
		msg: "message text here",
	},
	{
		id: 10,
		tenantName: "Sam Smith",
		read: false,
		msg: "message text here",
	},
	{
		id: 11,
		tenantName: "Sam Smith",
		read: false,
		msg: "message text here",
	},
	{
		id: 12,
		tenantName: "Sam Smith",
		read: false,
		msg: "message text here",
	},
	{
		id: 13,
		tenantName: "Sam Smith",
		read: false,
		msg: "message text here",
	},
	{
		id: 14,
		tenantName: "Sam Smith",
		read: false,
		msg: "message text here",
	},
	{
		id: 15,
		tenantName: "Sam Smith",
		read: false,
		msg: "message text here",
	},
	{
		id: 16,
		tenantName: "Sam Smith",
		read: false,
		msg: "message text here",
	},
	{
		id: 17,
		tenantName: "Sam Smith",
		read: false,
		msg: "message text here",
	},
	{
		id: 18,
		tenantName: "Sam Smith",
		read: false,
		msg: "house",
	},
	{
		id: 19,
		tenantName: "Sam Smith",
		read: false,
		msg: "message text here",
	},
	{
		id: 20,
		tenantName: "Sam Smith",
		read: false,
		msg: "message text here",
	},
];
